from openai import OpenAI

INSTRUCTIONS = """
    You are an internal knowledge assistant for a technology company. 
    Answer employee questions about the company tools, policies, and technical topics. 
    Keep answers concise: 2-3 sentences max. If you don't know the answer, say so and suggest who to contact.
"""

# Create a client that connects to the local Ollama server.
# Ollama does not use this API key, but the OpenAI client requires a value.
client = OpenAI(base_url="http://localhost:11434/v1", api_key="YOUR_API_KEY")

# Send a question to the selected language model and wait for its response.
reposponse = client.responses.create(
    model="llama3.2:3b",
    instructions=INSTRUCTIONS,
    input="How do I reset my password?",
)

# Print only the text generated by the model.
print(reposponse.output_text)